---
- name: 'Ensure {{ tpl_service.app_dir }} exists'
  file:
    path: '{{ tpl_service.app_dir }}'
    state: directory

# NOTE: Not sure if this is really needed and how it works for all provider, not just aws
# - name: '[main] {{ instance_task_name }} Generate .envrc'
#   blockinfile:
#     create: yes
#     dest: '{{ tpl_service.app_dir }}/.envrc'
#     marker: '# {mark} package'
#     block: |
#       export AWS_PROFILE={{ aws_package.provider.credential }}

- name: "Generate service's terraform.tfvars for app '{{ infrastructure_env }}'"
  template:
    src: terraform.tfvars.j2
    dest: '{{ tpl_service.app_dir }}/terraform.tfvars'
    force: no

#
# - name: '[tpl_service_app] Ensure the terragrunt temp directory is clean'
#   file:
#     path: '{{ ansible_env.HOME }}/.terragrunt }}'
#     state: absent
