---
- name: 'Ensure {{ resource_name }} directory exists'
  file:
    path: '{{ terraform_resource_provider_dir }}/{{ resource_name }}'
    state: directory

- name: 'Template {{ resource_name }}/main.tf'
  template:
    src: '{{ terraplate_provider_roles_dir }}/{{ resource_name }}/templates/main.tf.j2'
    dest: '{{ terraform_resource_provider_dir }}/{{ resource_name }}/main.tf'

- name: 'Include {{ resource_name }} vars'
  include_vars: '{{ terraplate_provider_roles_dir }}/{{ resource_name }}/vars/main.yml'

- name: 'Template {{ resource_name }}/signature.tf'
  template:
    src: 'signature.tf.j2'
    dest: '{{ terraform_resource_provider_dir }}/{{ resource_name }}/signature.tf'
