---
- include_role:
    name: terraplate

- name: Ensure the credentials file exists
  copy:
    dest: '{{ provision.tfvars.path }}/{{ provision.tfvars.name }}'
    force: no
    content: ''

- name: Write to .envrc
  blockinfile:
    create: yes
    dest: '{{ envrc_file }}'
    marker: '# {mark} {{ role_path }}'
    block: |
      export TF_VAR_s3_template_file_credentials_path={{ provision.tfvars.path }}

- name: Copy the template to the module
  copy:
    src: templates
    dest: '{{ res_dir }}'

- include_role:
    name: terraplate
    tasks_from: render
