---
- name: 'Add {{ tpl_resource.root_name }} variables to {{ tpl_resource.app.dest }}'
  blockinfile:
    create: no
    dest: '{{ tpl_resource.app.dest }}'
    marker: '# {mark} {{ tpl_resource.root_name }}'
    block: "{{ lookup('template', 'resource.tfvars.j2') }}"
  when: (tpl_resource.variables | length) > 0 and not tpl_resource.static
