---
- include_role:
    name: terraplate

- name: Write to .envrc
  blockinfile:
    create: yes
    dest: '{{ envrc_file }}'
    marker: '# {mark} {{ role_path }}'
    block: |
      export TF_VAR_ec2_key_pair_public_key_path={{ provision.tfvars.public_key_path }}

- include_role:
    name: terraplate
    tasks_from: render
