# NOTE: This set of tasks can be called by either component/tasks/main or package/tasks/render
# The pre-requisite is that the component instance properties hash 'c_this' has been set
---
- name: '[render] {{ instance_task_name }} Debug the component instance properties'
  debug: var='{{ item }}'
  with_items: [var_names, c_this]
  tags: debug

- name: '[render] {{ instance_task_name }} Set the provision properties'
  set_fact:
    provision:
      provider: '{{ package.provider | combine(c_this.class.vars.provider | default({})) | combine(c_this.vars.provider | default({})) }}'
      remote_state: '{{ package.remote_state | combine(c_this.class.vars.remote_state | default({})) | combine(c_this.vars.remote_state | default({})) }}'
      # remote_states: '{{ c_this.class.vars.remote_states | default({}) | combine(c_this.vars.remote_states | default({})) }}'
      remote_states: '{{ c_this.class.remote_states | default({}) | combine(c_this.vars.remote_states | default({})) }}'
      dependencies: '{{ c_this.class.dependencies | default([]) }}' # '| combine(c_this.vars.dependencies | default({})) }}'

- name: '[render] {{ instance_task_name }} Debug the provision properties'
  debug: var='{{ item }}'
  with_items: [component_dir, instance_dir, provision]
  tags: debug

- name: '[render] {{ instance_task_name }} Ensure the component and instance directory trees exist'
  file:
    path: '{{ item }}'
    state: directory
  with_items: ['{{ component_dir }}', '{{ instance_dir }}']
  tags: component

- name: '[render] {{ instance_task_name }} Template the Provider and Remote States'
  template:
    src: component.tf.j2
    dest: '{{ component_dir }}/_component.tf'
  tags: component

- name: '[render] {{ instance_task_name }} Add terragrunt config to tfvars'
  blockinfile:
    create: yes
    dest: '{{ tfvars_file }}'
    marker: '# {mark} component'
    block: |
      terragrunt = {
        terraform {
          source = "{{ component_path }}"
          extra_arguments "secrets" {
            arguments = [
              "-var-file=${get_tfvars_dir()}/{{ credentials_path }}/terraform/{{ provision.provider.credential }}.tfvars",
            ]
            commands = [
              "apply", "plan", "import", "push", "refresh", "destroy"
            ]
          }
        }
        include = {
          path = "${find_in_parent_folders()}"
        }
      {% if provision.dependencies is defined %}
        dependencies {
          paths = [
      {% for item in provision.dependencies %}
            "{{ item }}",
      {% endfor %}
          ]
        }
      {% endif %}
      }
      {% set pad_length = 60 %}
      region {{ ' ' * (pad_length - 7) }} = "{{ provision.provider.region }}"
      remote_state_bucket {{ ' ' * (pad_length - 20) }} = "{{ provision.remote_state.bucket }}"
      remote_state_region {{ ' ' * (pad_length - 20) }} = "{{ provision.remote_state.region }}"

      {% for key, value in provision.remote_states.iteritems() %}
      {% set key_pad = 'remote_state_key_' + (key | replace('-', '_')) + (' ' * (pad_length - 17 - (key | length))) %}
      {% if value.startswith('global') %}
      {{ key_pad }} = "{{ value }}"
      {% else %}
      {{ key_pad }} = "{{ package.directory }}/{{ infrastructure_env }}/{{ value }}"
      {% endif %}
      {% endfor %}
