---
- include_role:
    name: terraplate

- name: Write to .envrc
  blockinfile:
    create: yes
    dest: '{{ envrc_file }}'
    marker: '# {mark} {{ role_path }}'
    block: |
      export TF_VAR_iam_server_certificate_path={{ provision.tfvars.path }}

- include_role:
    name: terraplate
    tasks_from: render
