---
- name: Remove and re-create the component directory
  file:
    dest: '{{ tpl_component.app.dir }}'
    state: '{{ item }}'
  with_items: [absent, directory]

- name: 'Add terragrunt config to {{ tpl_component.app.tfvars_file }}'
  blockinfile:
    create: yes
    dest: '{{ tpl_component.app.tfvars_file }}'
    marker: '# {mark} component'
    block: "{{ lookup('template', 'component.tfvars.j2') }}"
