---
- name: Remove and re-create the component directory
  file:
    dest: '{{ tpl_component.app.dir }}'
    state: '{{ item }}'
  with_items: [absent, directory]

- name: 'Add terragrunt config to {{ tpl_component.app.tfvars_file }}'
  blockinfile:
    create: yes
    dest: '{{ tpl_component.app.tfvars_file }}'
    marker: '# {mark} component'
    block: |
      terragrunt = {
        terraform {
          source = "{{ tpl_component.app.path_to_lib }}"
        }
        include = {
          path = "${find_in_parent_folders()}"
        }
      {% if (tpl_component.dependencies | length) > 0 %}
        dependencies {
          paths = [
      {% for dependency in tpl_component.dependencies %}
            "{{ dependency }}",
      {% endfor %}
          ]
        }
      {% endif %}
      }
      {% set pad_length = 60 %}

      {# TODO set providers in tasks/main or in the component_#}
      {% set providers = tpl_component.needs.providers | default({}) %}
      {% for provider in providers %}
      {% set provider_vars = tpl_component.providers[provider] | default(tpl_service.default_providers[provider]) %}
      {% for var, value in provider_vars.iteritems() %}
      {% set key = 'provider_' + provider + '_' + var | replace('-', '_') %}
      {% set key_pad = ' ' * (pad_length - (key | length)) %}
      {{ key }}{{ key_pad }} = "{{ value }}"
      {% endfor %}
      {% endfor %}

      {% set remote_states = tpl_component.needs.remote_states | default({}) %}
      {% for provider in remote_states %}
      {% set provider_vars = tpl_component.remote_state_keys[provider] | default(tpl_service.default_remote_state_keys[provider]) %}
      {% for var, value in provider_vars.iteritems() %}
      {% set key = 'remote_state_' + provider + '_' + var | replace('-', '_') %}
      {% set key_pad = ' ' * (pad_length - (key | length)) %}
      {{ key }}{{ key_pad }} = "{{ value }}"
      {% endfor %}
      {% endfor %}

      {#}
      {% if xremote_states is defined %}
      {% for key, value in remote_states.iteritems() %}
      {% set key_pad = 'remote_state_key_' + (key | replace('-', '_')) + (' ' * (pad_length - 17 - (key | length))) %}
      {% if value.startswith('global') %}
      {{ key_pad }} = "{{ value }}"
      {% else %}
      {{ key_pad }} = "{{ package.directory }}/{{ infrastructure_env }}/{{ value }}"
      {% endif %}
      {% endfor %}
      {% endif %}
      {#}
